export { default as Shoppage } from "./Shoppage.tsx";
export { default as Cartpage } from "./Cartpage.tsx";
export { default as Detailpage } from "./Detailpage.tsx";
export { default as Loginpage } from "./Loginpage.tsx";
export { default as Registerpage } from "./Registrationpage.tsx";
export { default as NotFound } from "./NotFound.tsx";
export { default as Homepage } from "./Homepage.tsx";
export { default as Wishlist } from "./WishListPage.tsx";
export { default as Aboutpage } from "./AboutPage.tsx";
