name: Discord Notification on Update

on:
  push:
    branches:
      - ___-setup
      - development
      - main

    pull_request:
      branches:
        - main
        - development

jobs:
  discordNotification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Send Discord Notification
        run: |
          DISCORD_WEBHOOK_URL="https://discord.com/api/webhooks/1340895215338393743/D4ihOhzdWlZD03ovNYy2-YWXNn0y9GC1hgdIXz29ugkCpKG9eK90Hy6NmsK1qhPnbS_d"
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          COMMIT_URL="${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
          COLOR=${{ github.event_name == 'pull_request' && 16711680 || 9055202 }}
          curl -H "Content-Type: application/json" -X POST -d '{
            "embeds": [{
              "title": "Repository Updated!!",
              "description": "The repository **${{ github.repository }}** has been updated on branch **${{ github.ref_name }}** by **${{ github.actor }}**! 🚀",
              "color": '"$COLOR"',
              "fields": [
                {
                  "name": "Commit Message",
                  "value": "'"$COMMIT_MESSAGE"'"
                },
                {
                  "name": "Check out the changes here",
                  "value": "'"$COMMIT_URL"'"
                }
              ]
            }]
          }' $DISCORD_WEBHOOK_URL
