name: CI Merge

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  quality-checks-merge:
    name: Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Typescript type checking
        run: npm run type-check

      - name: Run ESLint (no fix)
        run: npm run lint

      - name: Run Prettier formatting check
        run: npm run format:check
