name: Create Vercel preview URL

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  build_and_deploy:
    name: Build & Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & Generate Preview on Vercel
        uses: amondnet/vercel-action@v25
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Link Preview URL
        run: |
          echo ${{ steps.vercel-deploy.outputs.preview-url }}
