name: Create Vercel preview URL

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  build_and_deploy:
    name: Build & Preview
    runs-on: ubuntu-latest
    environment: preview
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set ENV variables
        uses: dkershner6/vercel-set-env-action@v3
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: poke-markt-webshop
          envVariableKeys: VITE_API_URL
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          TARGET_VITE_API_URL: preview
          TYPE_VITE_API_URL: plain

      - name: Build & Generate Preview on Vercel
        uses: amondnet/vercel-action@v25
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Link Preview URL
        run: |
          echo ${{ steps.vercel-deploy.outputs.preview-url }}
