name: Create Vercel preview URL

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  build_and_deploy:
    name: Build & Preview
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Deploy to Vercel
        run: |
          npx vercel --token ${VERCEL_TOKEN} --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Link Preview URL
        run: |
          echo ${{ steps.vercel-deploy.outputs.preview-url }}
